heat_template_version: 2015-10-15

description: 3 single nodes fragment

parameters:
  key_pair:
    type: string
  network:
    type: string
    default: ""
  network01:
    type: string
  network02:
    type: string
  network03:
    type: string
  network04:
    type: string
  network05:
    type: string
  security_group:
    type: string
  network01_prefix:
    type: string
  network02_prefix:
    type: string
  network03_prefix:
    type: string
  network04_prefix:
    type: string
  network05_prefix:
    type: string
  network01_vip_address:
    type: json
    default: []
  network02_vip_address:
    type: json
    default: []
  network03_vip_address:
    type: json
    default: []
  network04_vip_address:
    type: json
    default: []
  network05_vip_address:
    type: json
    default: []
  instance01_name:
    type: string
  instance02_name:
    type: string
  instance03_name:
    type: string
  instance_domain:
    type: string
  instance_cluster:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_boot_timeout:
    type: number
    default: 3600
  instance_config_host:
    type: string
  instance_cloud_init:
    type: string
    default: ""

resources:
  instance01:
    type: MCP::SingleInstance5
    properties:
      key_pair: { get_param: key_pair }
      network: { get_param: network }
      network01: { get_param: network01 }
      network02: { get_param: network02 }
      network03: { get_param: network03 }
      network04: { get_param: network04 }
      network05: { get_param: network05 }
      security_group: { get_param: security_group }
      network01_prefix: { get_param: network01_prefix }
      network02_prefix: { get_param: network02_prefix }
      network03_prefix: { get_param: network03_prefix }
      network04_prefix: { get_param: network04_prefix }
      network05_prefix: { get_param: network05_prefix }
      network01_vip_address: { get_param: network01_vip_address }
      network02_vip_address: { get_param: network02_vip_address }
      network03_vip_address: { get_param: network03_vip_address }
      network04_vip_address: { get_param: network04_vip_address }
      network05_vip_address: { get_param: network05_vip_address }
      instance_name: { get_param: instance01_name }
      instance_domain: { get_param: instance_domain }
      instance_cluster: { get_param: instance_cluster }
      instance_zone:  { get_param: instance_zone }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_boot_timeout: { get_param: instance_boot_timeout }
      instance_config_host: { get_param: instance_config_host }
      instance_cloud_init: { get_param: instance_cloud_init }
  instance02:
    type: MCP::SingleInstance5
    properties:
      key_pair: { get_param: key_pair }
      network: { get_param: network }
      network01: { get_param: network01 }
      network02: { get_param: network02 }
      network03: { get_param: network03 }
      network04: { get_param: network04 }
      network05: { get_param: network05 }
      security_group: { get_param: security_group }
      network01_prefix: { get_param: network01_prefix }
      network02_prefix: { get_param: network02_prefix }
      network03_prefix: { get_param: network03_prefix }
      network04_prefix: { get_param: network04_prefix }
      network05_prefix: { get_param: network05_prefix }
      network01_vip_address: { get_param: network01_vip_address }
      network02_vip_address: { get_param: network02_vip_address }
      network03_vip_address: { get_param: network03_vip_address }
      network04_vip_address: { get_param: network04_vip_address }
      network05_vip_address: { get_param: network05_vip_address }
      instance_name: { get_param: instance02_name }
      instance_domain: { get_param: instance_domain }
      instance_cluster: { get_param: instance_cluster }
      instance_zone:  { get_param: instance_zone }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_boot_timeout: { get_param: instance_boot_timeout }
      instance_config_host: { get_param: instance_config_host }
      instance_cloud_init: { get_param: instance_cloud_init }
  instance03:
    type: MCP::SingleInstance5
    properties:
      key_pair: { get_param: key_pair }
      network: { get_param: network }
      network01: { get_param: network01 }
      network02: { get_param: network02 }
      network03: { get_param: network03 }
      network04: { get_param: network04 }
      network05: { get_param: network05 }
      security_group: { get_param: security_group }
      network01_prefix: { get_param: network01_prefix }
      network02_prefix: { get_param: network02_prefix }
      network03_prefix: { get_param: network03_prefix }
      network04_prefix: { get_param: network04_prefix }
      network05_prefix: { get_param: network05_prefix }
      network01_vip_address: { get_param: network01_vip_address }
      network02_vip_address: { get_param: network02_vip_address }
      network03_vip_address: { get_param: network03_vip_address }
      network04_vip_address: { get_param: network04_vip_address }
      network05_vip_address: { get_param: network05_vip_address }
      instance_name: { get_param: instance03_name }
      instance_domain: { get_param: instance_domain }
      instance_cluster: { get_param: instance_cluster }
      instance_zone:  { get_param: instance_zone }
      instance_os: { get_param: instance_os }
      instance_flavor: { get_param: instance_flavor }
      instance_image: { get_param: instance_image }
      instance_boot_timeout: { get_param: instance_boot_timeout }
      instance_config_host: { get_param: instance_config_host }
      instance_cloud_init: { get_param: instance_cloud_init }
