heat_template_version: 2015-10-15

description: Member of autoscaling cluster fragment with volumes

parameters:
  key_pair:
    type: string
  network:
    type: string
  security_group:
    type: string
  network01_prefix:
    type: string
  network02_prefix:
    type: string
  network03_prefix:
    type: string
  network04_prefix:
    type: string
  network05_prefix:
    type: string
  instance_name:
    type: string
  instance_domain:
    type: string
  instance_cluster:
    type: string
  instance_zone:
    type: string
  instance_os:
    type: string
  instance_flavor:
    type: string
  instance_image:
    type: string
  instance_boot_timeout:
    type: number
    default: 3600
  instance_config_host:
    type: string
  instance_cloud_init:
    type: string
    default: ""
  instance_lb:
    type: string
  instance_metadata:
    type: string
  volume_size:
    type: number
    default: 10
  volume_type:
    type: string
    default: ""

resources:
  instance_port01:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net01']] }
      allowed_address_pairs:
      - ip_address:
          list_join:
          - '.'
          - [ { get_param: network01_prefix }, '0/24' ]
      security_groups:
        - default
        - { get_param: security_group }
  instance_port02:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net02']] }
      allowed_address_pairs:
      - ip_address:
          list_join:
          - '.'
          - [ { get_param: network02_prefix }, '0/24' ]
      security_groups:
        - default
        - { get_param: security_group }
  instance_port03:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net03']] }
      allowed_address_pairs:
      - ip_address:
          list_join:
          - '.'
          - [ { get_param: network03_prefix }, '0/24' ]
      security_groups:
        - default
        - { get_param: security_group }
  instance_port04:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net04']] }
      allowed_address_pairs:
      - ip_address:
          list_join:
          - '.'
          - [ { get_param: network04_prefix }, '0/24' ]
      security_groups:
        - default
        - { get_param: security_group }
  instance_port05:
    type: OS::Neutron::Port
    properties:
      network_id: { list_join: ['-', [get_param: network, 'net05']] }
      allowed_address_pairs:
      - ip_address:
          list_join:
          - '.'
          - [ { get_param: network05_prefix }, '0/24' ]
      security_groups:
        - default
        - { get_param: security_group }
  instance_wait_handle:
    type: OS::Heat::WaitConditionHandle
  instance_wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: instance_wait_handle }
      timeout: { get_param: instance_boot_timeout }
  instance_volume01:
    type: OS::Cinder::Volume
    properties:
      name:
        list_join:
        - '.'
        - [ "volume01", { get_param: instance_name }, { get_param: instance_domain } ]
      size: { get_param: volume_size }
#      volume_type: { get_param: volume_type }
  instance_volume02:
    type: OS::Cinder::Volume
    properties:
      name:
        list_join:
        - '.'
        - [ "volume02", { get_param: instance_name }, { get_param: instance_domain } ]
      size: { get_param: volume_size }
#      volume_type: { get_param: volume_type }
  instance_volume03:
    type: OS::Cinder::Volume
    properties:
      name:
        list_join:
        - '.'
        - [ "volume03", { get_param: instance_name }, { get_param: instance_domain } ]
      size: { get_param: volume_size }
#      volume_type: { get_param: volume_type }
  instance_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: instance_image }
      image_update_policy: REBUILD
      flavor: { get_param: instance_flavor }
      block_device_mapping:
      - volume_id: { get_resource: instance_volume01 }
        device_name: vdb
      - volume_id: { get_resource: instance_volume02 }
        device_name: vdc
      - volume_id: { get_resource: instance_volume03 }
        device_name: vdd
      name:
        list_join:
        - '.'
        - [ { get_param: instance_name }, { get_param: instance_domain } ]
      availability_zone: { get_param: instance_zone }
      key_name: { get_param: key_pair }
      networks:
      - port: { get_resource: instance_port01 }
      - port: { get_resource: instance_port02 }
      - port: { get_resource: instance_port03 }
      - port: { get_resource: instance_port04 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: ../script/instance_boot.sh }
          params:
            $node_os: { get_param: instance_os }
            $node_hostname: { get_param: instance_name }
            $node_domain: { get_param: instance_domain }
            $cluster_name: { get_param: instance_cluster }
            $config_host: { get_param: config_host }
            $network01_prefix: { get_param: network01_prefix }
            $network02_prefix: { get_param: network02_prefix }
            $network03_prefix: { get_param: network03_prefix }
            $network04_prefix: { get_param: network04_prefix }
            $network05_prefix: { get_param: network05_prefix }
            $instance_cloud_init: { get_param: instance_cloud_init }
            $wait_condition_notify: { get_attr: [instance_wait_handle, curl_cli] }

outputs:
  instance_address:
    value: { get_attr: [instance_instance, first_address] }
    description: "Instance's private IP address"
  instance:
    value: { get_resource: instance_instance }
    description: "Instance"
